versions
version5617: spec
	<version: '5.617' imports: #('5.1-baseline' )>

	spec for: #'common' do: [
		spec blessing: #'stable'.
		spec description: 'version 5.617'.
		spec author: 'GuillermoPolito'.
		spec timestamp: '3/7/2016 22:48'.
		spec 
			package: 'AST-Core' with: 'AST-Core-TheIntegrator.403';
			package: 'Announcements-Core' with: 'Announcements-Core-EstebanLorenzano.65';
			package: 'CodeExport' with: 'CodeExport-TheIntegrator.17';
			package: 'CodeImport' with: 'CodeImport-TheIntegrator.81';
			package: 'CodeImportCommandLineHandlers' with: 'CodeImportCommandLineHandlers-TheIntegrator.5';
			package: 'Collections-Abstract' with: 'Collections-Abstract-TheIntegrator.313';
			package: 'Collections-Arithmetic' with: 'Collections-Arithmetic-TheIntegrator.20';
			package: 'Collections-Atomic' with: 'Collections-Atomic-TheIntegrator.16';
			package: 'Collections-Native' with: 'Collections-Native-TheIntegrator.19';
			package: 'Collections-Sequenceable' with: 'Collections-Sequenceable-TheIntegrator.234';
			package: 'Collections-Stack' with: 'Collections-Stack-TheIntegrator.10';
			package: 'Collections-Streams' with: 'Collections-Streams-TheIntegrator.188';
			package: 'Collections-Strings' with: 'Collections-Strings-TheIntegrator.399';
			package: 'Collections-Support' with: 'Collections-Support-TheIntegrator.65';
			package: 'Collections-Unordered' with: 'Collections-Unordered-TheIntegrator.227';
			package: 'Collections-Weak' with: 'Collections-Weak-TheIntegrator.100';
			package: 'Compression' with: 'Compression-TheIntegrator.171';
			package: 'FileSystem-Core' with: 'FileSystem-Core-TheIntegrator.193';
			package: 'FileSystem-Disk' with: 'FileSystem-Disk-TheIntegrator.92';
			package: 'Files' with: 'Files-TheIntegrator.411';
			package: 'Jobs' with: 'Jobs-TheIntegrator.28';
			package: 'Kernel' with: 'Kernel-TheIntegrator.2235';
			package: 'Monticello' with: 'Monticello-TheIntegrator.1113';
			package: 'Multilingual-Encodings' with: 'Multilingual-Encodings-TheIntegrator.61';
			package: 'Multilingual-Languages' with: 'Multilingual-Languages-TheIntegrator.50';
			package: 'Multilingual-TextConversion' with: 'Multilingual-TextConversion-TheIntegrator.81';
			package: 'Network-UUID' with: 'Network-UUID-TheIntegrator.39';
			package: 'OpalCompiler-Core' with: 'OpalCompiler-Core-TheIntegrator.786';
			package: 'Random-Core' with: 'Random-Core-TheIntegrator.4';
			package: 'RPackage-Core' with: 'RPackage-Core-TheIntegrator.422';
			package: 'Ring-Core-Containers' with: 'Ring-Core-Containers-TheIntegrator.43';
			package: 'Ring-Core-Kernel' with: 'Ring-Core-Kernel-TheIntegrator.237';
			package: 'Ring-Monticello' with: 'Ring-Monticello-TheIntegrator.40';
			package: 'RingChunkImporter' with: 'RingChunkImporter-TheIntegrator.4';
			package: 'Slot' with: 'Slot-TheIntegrator.723';
			package: 'System-Announcements' with: 'System-Announcements-TheIntegrator.108';
			package: 'System-BasicCommandLineHandler' with: 'System-BasicCommandLineHandler-EstebanLorenzano.13';
			package: 'System-Changes' with: 'System-Changes-TheIntegrator.292';
			package: 'System-CommandLine' with: 'System-CommandLine-TheIntegrator.181';
			package: 'System-CommandLineHandler' with: 'System-CommandLineHandler-TheIntegrator.12';
			package: 'System-Finalization' with: 'System-Finalization-TheIntegrator.28';
			package: 'System-Hashing' with: 'System-Hashing-TheIntegrator.47';
			package: 'System-Localization' with: 'System-Localization-TheIntegrator.100';
			package: 'System-Model' with: 'System-Model-TheIntegrator.2';
			package: 'System-Platforms' with: 'System-Platforms-TheIntegrator.81';
			package: 'System-Sources' with: 'System-Sources-TheIntegrator.46';
			package: 'System-Support' with: 'System-Support-TheIntegrator.1204';
			package: 'Traits' with: 'Traits-TheIntegrator.890';
			package: 'Transcript' with: 'Transcript-TheIntegrator.45';
			package: 'UIManager' with: 'UIManager-TheIntegrator.178';
			package: 'Compiler' with: 'Compiler-EstebanLorenzano.600';
			package: 'Text-Core' with: 'Text-Core-TheIntegrator.46';
			package: 'System-SessionManager' with: 'System-SessionManager-ChristopheDemarey.18';
			package: 'Zinc-Character-Encoding-Core' with: 'Zinc-Character-Encoding-Core-SvenVanCaekenberghe.45';
			package: 'Zinc-Resource-Meta-Core' with: 'Zinc-Resource-Meta-Core-PavelKrivanek.56';
			package: 'PharoBootstrap-Initialization' with: 'PharoBootstrap-Initialization-GuillermoPolito.9';
			package: 'NonInteractiveTranscript' with: 'NonInteractiveTranscript-TheIntegrator.25'. ].
