versions
version30864: spec
	<version: '3.864' imports: #('3.0-baseline')>
	spec
		for: #common
		do: [ 
			spec blessing: #stable.
			spec description: 'version 3.864'.
			spec package: 'AST-Core' with: 'AST-Core-MarcusDenker.208'.
			spec package: 'Announcements-Core' with: 'Announcements-Core-MarcusDenker.55'.
			spec package: 'ClassOrganizer-Core' with: 'ClassOrganizer-Core-TheIntegrator.30'.
			spec package: 'Collections-Abstract' with: 'Collections-Abstract-MarcusDenker.249'.
			spec package: 'Collections-Arrayed' with: 'Collections-Arrayed-EstebanLorenzano.69'.
			spec package: 'Collections-Native' with: 'Collections-Native-MarcusDenker.7'.
			spec package: 'Collections-Sequenceable' with: 'Collections-Sequenceable-StephaneDucasse.161'.
			spec package: 'Collections-Streams' with: 'Collections-Streams-MarcusDenker.160'.
			spec package: 'Collections-Strings' with: 'Collections-Strings-TheIntegrator.315'.
			spec package: 'Collections-Support' with: 'Collections-Support-SvenVanCaekenberghe.54'.
			spec package: 'Collections-Traits' with: 'Collections-Traits-MarcusDenker.17'.
			spec package: 'Collections-Unordered' with: 'Collections-Unordered-MarcusDenker.187'.
			spec package: 'Collections-Weak' with: 'Collections-Weak-MarcusDenker.86'.
			spec package: 'Kernel' with: 'Kernel-MarcusDenker.1753'.
			spec package: 'NonInteractiveTranscript' with: 'NonInteractiveTranscript-MarcusDenker.13'.
			spec package: 'OpalCompiler-Core' with: 'OpalCompiler-Core-MarcusDenker.485'.
			spec package: 'PackageInfo' with: 'PackageInfo-SvenVanCaekenberghe.117'.
			spec package: 'RPackage-Core' with: 'RPackage-Core-EstebanLorenzano.362'.
			spec package: 'Slot' with: 'Slot-MarcusDenker.427'.
			spec package: 'System-Announcements' with: 'System-Announcements-MarcusDenker.63'.
			spec package: 'System-Finalization' with: 'System-Finalization-StephaneDucasse.17'.
			spec package: 'System-Object Events' with: 'System-Object Events-MarcusDenker.13'.
			spec package: 'System-Support' with:'System-Support-MarcusDenker.1023'.
			spec package: 'Traits' with: 'Traits-EstebanLorenzano.641'.
			spec package: 'Transcript' with: 'Transcript-SvenVanCaekenberghe.21'. ].